### ISSUE TITLE
Can't start a project

### ISSUE THREAD

**Issue by Groctel** [castwide/gamefic-sdk#1]
I'm fairly new to Ruby and can't figure out how to start a new project.

The README says that running this should be enough:

```shell
gem install gamefic-sdk
gamefic init my_game
```

However, the second command returns this error:

```
Traceback (most recent call last):
	11: from /home/groctel/.gem/ruby/2.7.0/bin/gamefic:23:in `<main>'
	10: from /home/groctel/.gem/ruby/2.7.0/bin/gamefic:23:in `load'
	9: from /home/groctel/.gem/ruby/2.7.0/gems/gamefic-1.7.0/bin/gamefic:9:in `<top (required)>'
	8: from /home/groctel/.gem/ruby/2.7.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	7: from /home/groctel/.gem/ruby/2.7.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	6: from /home/groctel/.gem/ruby/2.7.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	5: from /home/groctel/.gem/ruby/2.7.0/gems/thor-0.20.3/lib/thor/command.rb:128:in `run'
	4: from /home/groctel/.gem/ruby/2.7.0/gems/thor-0.20.3/lib/thor/command.rb:29:in `run'
	3: from /home/groctel/.gem/ruby/2.7.0/gems/gamefic-1.7.0/lib/gamefic/shell.rb:49:in `method_missing'
	2: from /home/groctel/.gem/ruby/2.7.0/gems/gamefic-1.7.0/lib/gamefic/shell.rb:49:in `raise'
	1: from /home/groctel/.gem/ruby/2.7.0/gems/gamefic-1.7.0/lib/gamefic/shell.rb:49:in `exception'
/home/groctel/.gem/ruby/2.7.0/gems/thor-0.20.3/lib/thor/error.rb:50:in `initialize': wrong number of arguments (given 1, expected 3) (ArgumentError)
```

There's also no further documentation on this and the website doesn't have any docs whatsoever. What do I need to do in order to start a project and where can I find documentation on the engine?

**Comment by castwide** [comment]
The current gem (v1.7) is way out of sync with the current README, which documents the upcoming v2.0. Until v2.0 is released, you would need to install the gamefic gems from their repos. It's not a pretty process, but I can try to provide help if you want to give it a shot. Sorry for the inconvenience. I hope to publish v2.0 in the near future.

**Comment by Groctel** [comment]
Thanks for the reply!
If you're working on a 2.0 release I'll wait until it is out so I don't have to adapt my project to the upcoming changes. In the meantime, do you have some kind of development roadmap? I may be able to drop by from time to time and make a contribution to help you release earlier :D

**Comment by castwide** [comment]
Thanks for the offer. I'm working on updating the roadmap. Once it's ready to share, I'll be happy for any help I can get.

Good news for version 2, though. The new features were mostly finished. I just had to clean up some stale code that was cluttering the libraries. I'm going to set up some more tests, and barring unforeseen circumstances, I hope to publish the new release this weekend.

**Comment by Groctel** [comment]
I'll keep an eye on it then

**Comment by castwide** [comment]
Gamefic 2 is released. I've already pushed a few patches, so gamefic-sdk is up to 2.0.2.

I'll probably release more updates over the next few days, but it's stable enough that I've switched from using the development version to the published version for my own game projects.
