### ISSUE TITLE
Examples seem out of date for Gamefic 2.0

### ISSUE THREAD

**Issue by biscuitvile** [castwide/gamefic-sdk#2]
I apologize if I'm doing something wrong but the examples here no longer seem to work for Gamefic 2.0, or perhaps I need to specifically require something to make them work. In one particular case the API for connecting rooms has definitely changed. In another case libraries required in the examples cannot be found. Are these expected to work as-is right now or are they out of date?

I use this library with a student who is learning Ruby. In general much can be learned from reading the gamefic source, which is fine for me but difficult for a beginner. I'd love to see (or help you create) examples of some common adventure game idioms, for example to combine two items to create a new item in your inventory, or a clearer example of how locked doors between rooms work.

Thank you for the work on this project! It is really quite cool and is a great way for me to work with my student on something fun.

**Comment by castwide** [comment]
Thanks, I'm glad you find Gamefic useful!

You're right, the README is way out of date. You can find better doumentation here: https://gamefic.com/guides. The documentation is still a work in progress, but that should be the most recent version.

I'll update the README so at least the examples should work. If you come across anything else that's blatantly wrong besides how to connect rooms, please let me know.
